#### 1. libraries upload

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#### 2. Data load

In [6]:
churm_df= pd.read_csv('https://raw.githubusercontent.com/Haroldgio28/Probabilidad_de_impago/main/data/case%202/Churn%20Modeling.csv')
churm_df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

#### 3. Data exploration

In [7]:
# How many dimetions churm dataframe has?
'''
Churm dataframe hast 10.000 rows and 14 columns o variables
'''
churm_df.shape

(10000, 14)

In [8]:
# Info about dataframe
'''
Info from crum dataframe shows rows number and a detailed description of it's 14 rows
it hasn't null values

'''
churm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

| Column    | Description              | Variable type | Data type |
|-----------|--------------------------|---------------|-----------|
| RowNumber | Unique id for every row  | N/A           | int       |
| CustomerId | Unique id for every customer | N/A | int |
| Surname | Surname | Qualitative nominal data | object |
| CreditScore | credit score for customer | Qantitative discrete data | int |
| Geography | Geographic location | Qualitative Nominal data | object |
| Gender | Gender | Qualitative binary data | int |
| Age | age | quantitative discrete data | int |
| Tenure | Tenure | Quantitative discrete data | int |

In [9]:
# Here we separate numeric and categorical variables from churm data
numeric_var = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']
categorical_var = ['Geography', 'Gender', 'HasCrCard', 'IsActiveMember', 'Exited']

# now we will change data type for categorical varibales due is a good practice on data description
'''
When we change data type on a categorical variable we can choose between objet ans category
category is more efficient
'''
for categ in categorical_var:
    churm_df[categ] = churm_df[categ].astype('category')

In [10]:
churm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  category
 5   Gender           10000 non-null  category
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  category
 11  IsActiveMember   10000 non-null  category
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  category
dtypes: category(5), float64(2), int64(6), object(1)
memory usage: 752.7+ KB

In [11]:
# We explore how many unique values calumns has
churm_df['Tenure'].unique()

array([ 2,  1,  8,  7,  4,  6,  3, 10,  5,  9,  0])

In [12]:
churm_df['NumOfProducts'].unique()

array([1, 3, 2, 4])

In [13]:
churm_df['HasCrCard'].unique()

[1, 0]
Categories (2, int64): [0, 1]

In [14]:
churm_df['Exited'].unique()

[1, 0]
Categories (2, int64): [0, 1]

#### Estadistica descriptiva

In [15]:
# esta funcion nos muestra un resumen estadistico de los datos
#numericos que se ecuentran en el dataframe
churm_df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,EstimatedSalary
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,100090.239881
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,57510.492818
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,11.580000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,51002.110000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,100193.915000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,149388.247500
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,199992.480000

In [16]:
# Pudo tambien hacer un describe de las variables cualitativas o categoricas
churm_df.describe(include=object)

       Surname
count    10000
unique    2932
top      Smith
freq        32

In [ ]:
# con este comando puedo incluir todas las variables del dataframe para hacer el describe
churm_df.describe(include='all')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000,10000.000000,10000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0,10000.0,10000.000000,10000.0
unique,NaN,NaN,2932,NaN,3,2,NaN,NaN,NaN,NaN,2.0,2.0,NaN,2.0
top,NaN,NaN,Smith,NaN,France,Male,NaN,NaN,NaN,NaN,1.0,1.0,NaN,0.0
freq,NaN,NaN,32,NaN,5014,5457,NaN,NaN,NaN,NaN,7055.0,5151.0,NaN,7963.0
mean,5000.50000,1.569094e+07,NaN,650.528800,NaN,NaN,38.921800,5.012800,76485.889288,1.530200,NaN,NaN,100090.239881,NaN
std,2886.89568,7.193619e+04,NaN,96.653299,NaN,NaN,10.487806,2.892174,62397.405202,0.581654,NaN,NaN,57510.492818,NaN
min,1.00000,1.556570e+07,NaN,350.000000,NaN,NaN,18.000000,0.000000,0.000000,1.000000,NaN,NaN,11.580000,NaN
25%,2500.75000,1.562853e+07,NaN,584.000000,NaN,NaN,32.000000,3.000000,0.000000,1.000000,NaN,NaN,51002.110000,NaN
50%,5000.50000,1.569074e+07,NaN,652.000000,NaN,NaN,37.000000,5.000000,97198.540000,1.000000,NaN,NaN,100193.915000,NaN
75%,7500.25000,1.575323e+07,NaN,718.000000,NaN,NaN,44.000000,7.000000,127644.240000,2.000000,NaN,NaN,149388.247500,NaN
max,10000.00000,1.581569e+07,NaN,850.000000,NaN,NaN,92.000000,10.000000,250898.090000,4.000000,NaN,NaN,199992.480000,NaN